// Map of school IDs in schools.json → official athletics domain.
// These are domains I'm reasonably confident about (long-stable subdomains
// used by major college athletics departments). Empty entries fall back to
// a Google-search-driven discovery step inside the scraper.
//
// IMPORTANT: this file does not assert that any specific URL on the domain
// is current. The scraper still validates each fetch and reports failures.

export const ATHLETICS_DOMAINS: Record<string, string> = {
  // ── ACC ──
  unc: 'goheels.com',
  duke: 'goduke.com',
  virginia: 'virginiasports.com',
  fsu: 'seminoles.com',
  ncstate: 'gopack.com',
  wakeforest: 'godeacs.com',
  bostoncollege: 'bceagles.com',
  louisville: 'gocards.com',
  pitt: 'pittsburghpanthers.com',
  virginiatech: 'hokiesports.com',
  miami: 'miamihurricanes.com',
  syracuse: 'cuse.com',
  cal: 'calbears.com',
  clemson: 'clemsontigers.com',
  notredame: 'fightingirish.com',
  stanford: 'gostanford.com',

  // ── SEC ──
  alabama: 'rolltide.com',
  arkansas: 'arkansasrazorbacks.com',
  auburn: 'auburntigers.com',
  florida: 'floridagators.com',
  georgia: 'georgiadogs.com',
  kentucky: 'ukathletics.com',
  lsu: 'lsusports.net',
  olemiss: 'olemisssports.com',
  missState: 'hailstate.com',
  missouri: 'mutigers.com',
  southcarolina: 'gamecocksonline.com',
  tennessee: 'utsports.com',
  texas: 'texassports.com',
  tamu: '12thman.com',
  vanderbilt: 'vucommodores.com',
  oklahoma: 'soonersports.com',

  // ── Big Ten ──
  michigan: 'mgoblue.com',
  michiganstate: 'msuspartans.com',
  ohiostate: 'ohiostatebuckeyes.com',
  pennstate: 'gopsusports.com',
  rutgers: 'scarletknights.com',
  wisconsin: 'uwbadgers.com',
  iowa: 'hawkeyesports.com',
  illinois: 'fightingillini.com',
  minnesota: 'gophersports.com',
  nebraska: 'huskers.com',
  northwestern: 'nusports.com',
  indiana: 'iuhoosiers.com',
  maryland: 'umterps.com',
  ucla: 'uclabruins.com',
  usc: 'usctrojans.com',
  oregon: 'goducks.com',
  oregonstate: 'osubeavers.com',
  washington: 'gohuskies.com',

  // ── Big 12 ──
  baylor: 'baylorbears.com',
  byu: 'byucougars.com',
  colorado: 'cubuffs.com',
  cincinnati: 'gobearcats.com',
  houston: 'uhcougars.com',
  iowastate: 'cyclones.com',
  kansas: 'kuathletics.com',
  kstate: 'kstatesports.com',
  okstate: 'okstate.com',
  tcu: 'gofrogs.com',
  utah: 'utahutes.com',
  ucf: 'ucfknights.com',
  wvu: 'wvusports.com',
  arizona: 'arizonawildcats.com',
  arizonastate: 'thesundevils.com',

  // ── Big East ──
  georgetown: 'guhoyas.com',
  marquette: 'gomarquette.com',
  uconn: 'uconnhuskies.com',
  creighton: 'gocreighton.com',
  providence: 'friars.com',
  stjohns: 'redstormsports.com',

  // ── WCC ──
  portland: 'portlandpilots.com',
  santaclara: 'santaclarabroncos.com',
  gonzaga: 'gozags.com',
  sandiego: 'usdtoreros.com',
  stmarys: 'smcgaels.com',
  sanfrancisco: 'usfdons.com',
  lmu: 'lmulions.com',

  // ── A-10 / Big West / others ──
  slu: 'slubillikens.com',
  davidson: 'davidsonwildcats.com',
  vcu: 'vcuathletics.com',
  saintjoes: 'sjuhawks.com',
  denver: 'denverpioneers.com',
  ucsb: 'ucsbgauchos.com',
  uci: 'ucirvinesports.com',
  fgcu: 'fgcuathletics.com',
  liberty: 'liberty.edu',
  newmexico: 'golobos.com',
  smu: 'smumustangs.com',
  northtexas: 'meangreensports.com',
  utrgv: 'goutrgv.com',
  appstate: 'appstatesports.com',
  jamesmadison: 'jmusports.com',
  highpoint: 'highpointpanthers.com',
  belmont: 'belmontbruins.com',
  elon: 'elonphoenix.com',
  ewu: 'goeags.com',
  sacstate: 'hornetsports.com',
  grandcanyon: 'gculopes.com',
  uiw: 'uiwcardinals.com',
  akron: 'gozips.com',
  williamary: 'tribeathletics.com',
  usf: 'gousfbulls.com',
  olddominion: 'odusports.com',
  coastal: 'goccusports.com',

  // ── Ivy League ──
  harvard: 'gocrimson.com',
  yale: 'yalebulldogs.com',
  princeton: 'goprincetontigers.com',
  penn: 'pennathletics.com',
  cornell: 'cornellbigred.com',
  columbia: 'gocolumbialions.com',
  dartmouth: 'dartmouthsports.com',
  brown: 'brownbears.com',

  // ── D2 selected ──
  // Southeast
  leniorrhyne: 'lrathletics.com',
  floridasouthern: 'mocathletics.com',
  barry: 'bucathletics.com',
  eckerd: 'eckerd.edu',
  queens: 'queensathletics.com',
  wingate: 'wingateathletics.com',
  carsonNewman: 'cneaglesports.com',
  montevallo: 'falconsathletics.com',
  valdostaState: 'vstateblazers.com',
  northGeorgia: 'ngaathletics.com',
  // South Central
  mst: 'minerathletics.com',
  centralMissouri: 'ucmathletics.com',
  rockhurst: 'rockhurstathletics.com',
  mwstate: 'msuwathletics.com',
  wtamu: 'buffsathletics.com',
  enmu: 'gohoundogs.com',
  findlay: 'gooilers.com',
  // West
  calpolyPomona: 'broncoathletics.com',
  fortlewis: 'skayhawks.com',
  // Midwest
  minnStateMankato: 'msumavericks.com',
  stCloudState: 'huskiesathletics.com',
  // East
  shippensburg: 'raiderssports.com',
  setonhill: 'shugriffins.com',
  tampa: 'tampaspartans.com',
  rollins: 'rollinssports.com',
  gvsu: 'gvsulakers.com',
  mines: 'minesathletics.com',
  westchester: 'wcugoldenrams.com',
  saintanselm: 'saintanselmhawks.com',
  bentley: 'bentleyfalcons.com',
  lemoyne: 'gldolphins.com',
  wwu: 'wwuvikings.com',
  spu: 'gospufalcons.com',
  lewis: 'lewisflyers.com',
  trumanstate: 'trumanbulldogs.com',
  mercyhurst: 'hurstathletics.com',
  ashland: 'goashlandeagles.com',
  tiffin: 'gotiffindragons.com',
  saintRose: 'goldenknights.com',
  franklinpierce: 'fpuathletics.com',

  // ── D3 selected ──
  jhu: 'hopkinssports.com',
  haverford: 'haverfordathletics.com',
  swarthmore: 'swarthmoreathletics.com',
  washcoll: 'washingtoncollegesports.com',
  cms: 'cmsathletics.com',
  occidental: 'oxyathletics.com',
  caltech: 'gocaltech.com',
  rit: 'ritathletics.com',
  vassar: 'vassarathletics.com',
  skidmore: 'skidmoreathletics.com',
  stolaf: 'stolafathletics.com',
  carleton: 'athletics.carleton.edu',
  macalester: 'athletics.macalester.edu',
  gustavus: 'gogusties.com',
  kenyon: 'kenyonathletics.com',
  wittenberg: 'wittenbergtigers.com',
  depauw: 'depauwtigers.com',
  lynchburg: 'lynchburgsports.com',
  wlu: 'generalssports.com',
  mit: 'mitathletics.com',
  stevens: 'stevensducks.com',
  cnu: 'cnusports.com',
  rpi: 'rpiathletics.com',
  conncoll: 'conncollcamels.com',
  loras: 'lorasathletics.com',
  trinitytx: 'trinitytigers.com',
  otterbein: 'otterbeincardinals.com',
  wabash: 'sportswabash.com',
  smith: 'smithpioneers.com',
  brynmawr: 'athletics.brynmawr.edu',
  amherst: 'athletics.amherst.edu',
  bates: 'gobatesbobcats.com',
  bowdoin: 'athletics.bowdoin.edu',
  brandeis: 'gojudges.com',
  carnegieMellon: 'athletics.cmu.edu',
  chapman: 'chapmanathletics.com',
  colby: 'colbyathletics.com',
  cortland: 'cortlandreddragons.com',
  cwru: 'athletics.case.edu',
  denison: 'denisonbigred.com',
  dickinson: 'godickinsonred.com',
  emory: 'emoryathletics.com',
  franklinMarshall: 'godiplomats.com',
  gettysburg: 'gettysburgsports.com',
  hamilton: 'athletics.hamilton.edu',
  hardinSimmons: 'hsuathletics.com',
  hope: 'athletics.hope.edu',
  ithaca: 'athletics.ithaca.edu',
  lycoming: 'lycomingathletics.com',
  middlebury: 'athletics.middlebury.edu',
  muhlenberg: 'muhlenbergsports.com',
  nyu: 'gonyuathletics.com',
  ohioWesleyan: 'battlingbishops.com',
  pomona: 'sagehens.com',
  rochester: 'uofrathletics.com',
  rowan: 'rowanathletics.com',
  trinityHartford: 'bantamsports.com',
  tufts: 'gotuftsjumbos.com',
  uchicago: 'athletics.uchicago.edu',
  washu: 'bearsports.com',
  wesleyan: 'athletics.wesleyan.edu',
  wheaton: 'athletics.wheaton.edu',
  williams: 'gowilliams.com',
  messiah: 'gomessiah.com',
  calvin: 'calvinknights.com',

  // ── NAIA / JUCO selected ──
  lindseywilson: 'athletics.lindsey.edu',
  friendsU: 'friendsfalcons.com',
  ottawaU: 'ottawabraveathletics.com',
  columbiamoNAIA: 'athletics.ccis.edu',
  saintmartin: 'saintsathletics.com',
  northwestNazarene: 'nnu.edu',
  tyler: 'tylertigers.com',
  hutchinson: 'athletics.hutchcc.edu',
  bartonCounty: 'bartonathletics.com',
  sewardCounty: 'gogreats.com',
  cowley: 'cowleycollege.edu',
  trinityValley: 'athletics.tvcc.edu',
  northeastOkla: 'neoam.edu',
  sanjacinto: 'athletics.sjcd.edu',
  cloudcounty: 'cloudcc.edu',
  tampa2: 'aicyellowjackets.com',
  doane: 'doanetigers.com',
  concordiaNE: 'cunebulldogs.com',
  briarCliff: 'bcucharger.com',
  okcu: 'okcustars.com',
  mastersU: 'gomasters.com',
  keiser: 'keisersuncoasts.com',
  williamcarey: 'wmcareyathletics.com',
  harding: 'hardingsports.com',
  drury: 'drurypanthers.com',
  morningside: 'morningsidemustangs.com',
  northwesternIowa: 'nwcraiders.com',
  grandview: 'gvvikings.com',
  mhbu: 'mbubearcats.com',
  indianatech: 'indianatechwarriors.com',
  indianapolisU: 'athletics.uindy.edu',
}
