-- supabase/migrations/005_coach_portal.sql
-- Coach-side portal: college coaches "claim" their program with an email, see
-- which athletes have shown interest and edit their roster needs to keep the
-- Roster Intelligence feed fresh.

-- ── Coach-side portal: claimed programs ─────────────────────────────────────
-- A college coach claims a program (verified by email match against schools.json's
-- coach_email field). The "claim" lets them log in via magic link, edit their
-- roster needs (which feeds the Roster Intelligence + Open Spots data), and see
-- a feed of athletes who've emailed them through KickrIQ.
create table if not exists claimed_programs (
  id                 uuid primary key default gen_random_uuid(),
  school_id          text not null,                    -- matches schools.json id
  school_name        text not null default '',
  gender             text not null check (gender in ('mens','womens')),
  coach_email        text not null,                    -- normalized lowercase
  coach_name         text not null default '',
  coach_user_id      uuid references auth.users(id) on delete set null,
  -- Coach-curated overrides for the public feed; null means use the data
  -- generated by the system. Prevents the coach having to rebuild from scratch.
  needs_overrides    jsonb,                            -- [{position, level}, ...]
  notes_override     text,
  is_verified        boolean not null default false,
  claimed_at         timestamptz not null default now(),
  unique (school_id, gender)
);

create index if not exists claimed_programs_coach_user_idx on claimed_programs(coach_user_id);
create index if not exists claimed_programs_coach_email_idx on claimed_programs(coach_email);

alter table claimed_programs enable row level security;

create policy "Coach reads own claim"
  on claimed_programs for select
  using (auth.uid() = coach_user_id);
create policy "Coach updates own claim"
  on claimed_programs for update
  using (auth.uid() = coach_user_id)
  with check (auth.uid() = coach_user_id);
-- Inserts go through the server so we can validate the email match against
-- schools.json before granting a claim. No direct anon-insert policy.
